// This file is autogenerated. Do not edit by hand.
// To regenerate from schema, run `cargo run -p generator`.

using System;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Dap
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Command
    {
        [EnumMember(Value = "cancel")]
        Cancel,
        [EnumMember(Value = "runInTerminal")]
        RunInTerminal,
        [EnumMember(Value = "startDebugging")]
        StartDebugging,
        [EnumMember(Value = "initialize")]
        Initialize,
        [EnumMember(Value = "configurationDone")]
        ConfigurationDone,
        [EnumMember(Value = "launch")]
        Launch,
        [EnumMember(Value = "attach")]
        Attach,
        [EnumMember(Value = "restart")]
        Restart,
        [EnumMember(Value = "disconnect")]
        Disconnect,
        [EnumMember(Value = "terminate")]
        Terminate,
        [EnumMember(Value = "breakpointLocations")]
        BreakpointLocations,
        [EnumMember(Value = "setBreakpoints")]
        SetBreakpoints,
        [EnumMember(Value = "setFunctionBreakpoints")]
        SetFunctionBreakpoints,
        [EnumMember(Value = "setExceptionBreakpoints")]
        SetExceptionBreakpoints,
        [EnumMember(Value = "dataBreakpointInfo")]
        DataBreakpointInfo,
        [EnumMember(Value = "setDataBreakpoints")]
        SetDataBreakpoints,
        [EnumMember(Value = "setInstructionBreakpoints")]
        SetInstructionBreakpoints,
        [EnumMember(Value = "continue")]
        Continue,
        [EnumMember(Value = "next")]
        Next,
        [EnumMember(Value = "stepIn")]
        StepIn,
        [EnumMember(Value = "stepOut")]
        StepOut,
        [EnumMember(Value = "stepBack")]
        StepBack,
        [EnumMember(Value = "reverseContinue")]
        ReverseContinue,
        [EnumMember(Value = "restartFrame")]
        RestartFrame,
        [EnumMember(Value = "goto")]
        Goto,
        [EnumMember(Value = "pause")]
        Pause,
        [EnumMember(Value = "stackTrace")]
        StackTrace,
        [EnumMember(Value = "scopes")]
        Scopes,
        [EnumMember(Value = "variables")]
        Variables,
        [EnumMember(Value = "setVariable")]
        SetVariable,
        [EnumMember(Value = "source")]
        Source,
        [EnumMember(Value = "threads")]
        Threads,
        [EnumMember(Value = "terminateThreads")]
        TerminateThreads,
        [EnumMember(Value = "modules")]
        Modules,
        [EnumMember(Value = "loadedSources")]
        LoadedSources,
        [EnumMember(Value = "evaluate")]
        Evaluate,
        [EnumMember(Value = "setExpression")]
        SetExpression,
        [EnumMember(Value = "stepInTargets")]
        StepInTargets,
        [EnumMember(Value = "gotoTargets")]
        GotoTargets,
        [EnumMember(Value = "completions")]
        Completions,
        [EnumMember(Value = "exceptionInfo")]
        ExceptionInfo,
        [EnumMember(Value = "readMemory")]
        ReadMemory,
        [EnumMember(Value = "writeMemory")]
        WriteMemory,
        [EnumMember(Value = "disassemble")]
        Disassemble,
        [EnumMember(Value = "locations")]
        Locations,
    }

    public partial abstract class Request
    {
        private partial static Request ParseInternal(JObject message)
        {
            switch (message.Value<Dap.Command>("command"))
            {
                case Dap.Command.Cancel:
                    return message.ToObject<CancelRequest>();
                case Dap.Command.RunInTerminal:
                    return message.ToObject<RunInTerminalRequest>();
                case Dap.Command.StartDebugging:
                    return message.ToObject<StartDebuggingRequest>();
                case Dap.Command.Initialize:
                    return message.ToObject<InitializeRequest>();
                case Dap.Command.ConfigurationDone:
                    return message.ToObject<ConfigurationDoneRequest>();
                case Dap.Command.Launch:
                    return message.ToObject<LaunchRequest>();
                case Dap.Command.Attach:
                    return message.ToObject<AttachRequest>();
                case Dap.Command.Restart:
                    return message.ToObject<RestartRequest>();
                case Dap.Command.Disconnect:
                    return message.ToObject<DisconnectRequest>();
                case Dap.Command.Terminate:
                    return message.ToObject<TerminateRequest>();
                case Dap.Command.BreakpointLocations:
                    return message.ToObject<BreakpointLocationsRequest>();
                case Dap.Command.SetBreakpoints:
                    return message.ToObject<SetBreakpointsRequest>();
                case Dap.Command.SetFunctionBreakpoints:
                    return message.ToObject<SetFunctionBreakpointsRequest>();
                case Dap.Command.SetExceptionBreakpoints:
                    return message.ToObject<SetExceptionBreakpointsRequest>();
                case Dap.Command.DataBreakpointInfo:
                    return message.ToObject<DataBreakpointInfoRequest>();
                case Dap.Command.SetDataBreakpoints:
                    return message.ToObject<SetDataBreakpointsRequest>();
                case Dap.Command.SetInstructionBreakpoints:
                    return message.ToObject<SetInstructionBreakpointsRequest>();
                case Dap.Command.Continue:
                    return message.ToObject<ContinueRequest>();
                case Dap.Command.Next:
                    return message.ToObject<NextRequest>();
                case Dap.Command.StepIn:
                    return message.ToObject<StepInRequest>();
                case Dap.Command.StepOut:
                    return message.ToObject<StepOutRequest>();
                case Dap.Command.StepBack:
                    return message.ToObject<StepBackRequest>();
                case Dap.Command.ReverseContinue:
                    return message.ToObject<ReverseContinueRequest>();
                case Dap.Command.RestartFrame:
                    return message.ToObject<RestartFrameRequest>();
                case Dap.Command.Goto:
                    return message.ToObject<GotoRequest>();
                case Dap.Command.Pause:
                    return message.ToObject<PauseRequest>();
                case Dap.Command.StackTrace:
                    return message.ToObject<StackTraceRequest>();
                case Dap.Command.Scopes:
                    return message.ToObject<ScopesRequest>();
                case Dap.Command.Variables:
                    return message.ToObject<VariablesRequest>();
                case Dap.Command.SetVariable:
                    return message.ToObject<SetVariableRequest>();
                case Dap.Command.Source:
                    return message.ToObject<SourceRequest>();
                case Dap.Command.Threads:
                    return message.ToObject<ThreadsRequest>();
                case Dap.Command.TerminateThreads:
                    return message.ToObject<TerminateThreadsRequest>();
                case Dap.Command.Modules:
                    return message.ToObject<ModulesRequest>();
                case Dap.Command.LoadedSources:
                    return message.ToObject<LoadedSourcesRequest>();
                case Dap.Command.Evaluate:
                    return message.ToObject<EvaluateRequest>();
                case Dap.Command.SetExpression:
                    return message.ToObject<SetExpressionRequest>();
                case Dap.Command.StepInTargets:
                    return message.ToObject<StepInTargetsRequest>();
                case Dap.Command.GotoTargets:
                    return message.ToObject<GotoTargetsRequest>();
                case Dap.Command.Completions:
                    return message.ToObject<CompletionsRequest>();
                case Dap.Command.ExceptionInfo:
                    return message.ToObject<ExceptionInfoRequest>();
                case Dap.Command.ReadMemory:
                    return message.ToObject<ReadMemoryRequest>();
                case Dap.Command.WriteMemory:
                    return message.ToObject<WriteMemoryRequest>();
                case Dap.Command.Disassemble:
                    return message.ToObject<DisassembleRequest>();
                case Dap.Command.Locations:
                    return message.ToObject<LocationsRequest>();
                default:
                    throw new Exception($"unknown request command: {command}");
            }
        }
    }

    /// The `cancel` request is used by the client in two situations:
    /// - to indicate that it is no longer interested in the result produced by a specific request issued earlier
    /// - to cancel a progress sequence.
    /// Clients should only call this request if the corresponding capability `supportsCancelRequest` is true.
    /// This request has a hint characteristic: a debug adapter can only be expected to make a 'best effort' in honoring this request but there are no guarantees.
    /// The `cancel` request may return an error if it could not cancel an operation but a client should refrain from presenting this error to end users.
    /// The request that got cancelled still needs to send a response back. This can either be a normal result (`success` attribute true) or an error response (`success` attribute false and the `message` set to `cancelled`).
    /// Returning partial results from a cancelled request is possible but please note that a client has no generic way for detecting that a response is partial or not.
    /// The progress that got cancelled still needs to send a `progressEnd` event back.
    ///  A client should not assume that progress just got cancelled after sending the `cancel` request.
    public sealed class CancelRequest : Request<CancelArguments>
    {
        public override Dap.Command Command => Dap.Command.Cancel;
    }

    /// This request is sent from the debug adapter to the client to run a command in a terminal.
    /// This is typically used to launch the debuggee in a terminal provided by the client.
    /// This request should only be called if the corresponding client capability `supportsRunInTerminalRequest` is true.
    /// Client implementations of `runInTerminal` are free to run the command however they choose including issuing the command to a command line interpreter (aka 'shell'). Argument strings passed to the `runInTerminal` request must arrive verbatim in the command to be run. As a consequence, clients which use a shell are responsible for escaping any special shell characters in the argument strings to prevent them from being interpreted (and modified) by the shell.
    /// Some users may wish to take advantage of shell processing in the argument strings. For clients which implement `runInTerminal` using an intermediary shell, the `argsCanBeInterpretedByShell` property can be set to true. In this case the client is requested not to escape any special shell characters in the argument strings.
    public sealed class RunInTerminalRequest : Request<RunInTerminalRequestArguments>
    {
        public override Dap.Command Command => Dap.Command.RunInTerminal;
    }

    /// This request is sent from the debug adapter to the client to start a new debug session of the same type as the caller.
    /// This request should only be sent if the corresponding client capability `supportsStartDebuggingRequest` is true.
    /// A client implementation of `startDebugging` should start a new debug session (of the same type as the caller) in the same way that the caller's session was started. If the client supports hierarchical debug sessions, the newly created session can be treated as a child of the caller session.
    public sealed class StartDebuggingRequest : Request<StartDebuggingRequestArguments>
    {
        public override Dap.Command Command => Dap.Command.StartDebugging;
    }

    /// The `initialize` request is sent as the first request from the client to the debug adapter in order to configure it with client capabilities and to retrieve capabilities from the debug adapter.
    /// Until the debug adapter has responded with an `initialize` response, the client must not send any additional requests or events to the debug adapter.
    /// In addition the debug adapter is not allowed to send any requests or events to the client until it has responded with an `initialize` response.
    /// The `initialize` request may only be sent once.
    public sealed class InitializeRequest : Request<InitializeRequestArguments>
    {
        public override Dap.Command Command => Dap.Command.Initialize;
    }

    /// This request indicates that the client has finished initialization of the debug adapter.
    /// So it is the last request in the sequence of configuration requests (which was started by the `initialized` event).
    /// Clients should only call this request if the corresponding capability `supportsConfigurationDoneRequest` is true.
    public sealed class ConfigurationDoneRequest : Request<ConfigurationDoneArguments>
    {
        public override Dap.Command Command => Dap.Command.ConfigurationDone;
    }

    /// This launch request is sent from the client to the debug adapter to start the debuggee with or without debugging (if `noDebug` is true).
    /// Since launching is debugger/runtime specific, the arguments for this request are not part of this specification.
    public sealed class LaunchRequest : GenericRequest
    {
        public override Dap.Command Command => Dap.Command.Launch;
    }

    /// The `attach` request is sent from the client to the debug adapter to attach to a debuggee that is already running.
    /// Since attaching is debugger/runtime specific, the arguments for this request are not part of this specification.
    public sealed class AttachRequest : GenericRequest
    {
        public override Dap.Command Command => Dap.Command.Attach;
    }

    /// Restarts a debug session. Clients should only call this request if the corresponding capability `supportsRestartRequest` is true.
    /// If the capability is missing or has the value false, a typical client emulates `restart` by terminating the debug adapter first and then launching it anew.
    public sealed class RestartRequest : GenericRequest
    {
        public override Dap.Command Command => Dap.Command.Restart;
    }

    /// The `disconnect` request asks the debug adapter to disconnect from the debuggee (thus ending the debug session) and then to shut down itself (the debug adapter).
    /// In addition, the debug adapter must terminate the debuggee if it was started with the `launch` request. If an `attach` request was used to connect to the debuggee, then the debug adapter must not terminate the debuggee.
    /// This implicit behavior of when to terminate the debuggee can be overridden with the `terminateDebuggee` argument (which is only supported by a debug adapter if the corresponding capability `supportTerminateDebuggee` is true).
    public sealed class DisconnectRequest : Request<DisconnectArguments>
    {
        public override Dap.Command Command => Dap.Command.Disconnect;
    }

    /// The `terminate` request is sent from the client to the debug adapter in order to shut down the debuggee gracefully. Clients should only call this request if the capability `supportsTerminateRequest` is true.
    /// Typically a debug adapter implements `terminate` by sending a software signal which the debuggee intercepts in order to clean things up properly before terminating itself.
    /// Please note that this request does not directly affect the state of the debug session: if the debuggee decides to veto the graceful shutdown for any reason by not terminating itself, then the debug session just continues.
    /// Clients can surface the `terminate` request as an explicit command or they can integrate it into a two stage Stop command that first sends `terminate` to request a graceful shutdown, and if that fails uses `disconnect` for a forceful shutdown.
    public sealed class TerminateRequest : Request<TerminateArguments>
    {
        public override Dap.Command Command => Dap.Command.Terminate;
    }

    /// The `breakpointLocations` request returns all possible locations for source breakpoints in a given range.
    /// Clients should only call this request if the corresponding capability `supportsBreakpointLocationsRequest` is true.
    public sealed class BreakpointLocationsRequest : Request<BreakpointLocationsArguments>
    {
        public override Dap.Command Command => Dap.Command.BreakpointLocations;
    }

    /// Sets multiple breakpoints for a single source and clears all previous breakpoints in that source.
    /// To clear all breakpoint for a source, specify an empty array.
    /// When a breakpoint is hit, a `stopped` event (with reason `breakpoint`) is generated.
    public sealed class SetBreakpointsRequest : Request<SetBreakpointsArguments>
    {
        public override Dap.Command Command => Dap.Command.SetBreakpoints;
    }

    /// Replaces all existing function breakpoints with new function breakpoints.
    /// To clear all function breakpoints, specify an empty array.
    /// When a function breakpoint is hit, a `stopped` event (with reason `function breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsFunctionBreakpoints` is true.
    public sealed class SetFunctionBreakpointsRequest : Request<SetFunctionBreakpointsArguments>
    {
        public override Dap.Command Command => Dap.Command.SetFunctionBreakpoints;
    }

    /// The request configures the debugger's response to thrown exceptions. Each of the `filters`, `filterOptions`, and `exceptionOptions` in the request are independent configurations to a debug adapter indicating a kind of exception to catch. An exception thrown in a program should result in a `stopped` event from the debug adapter (with reason `exception`) if any of the configured filters match.
    /// Clients should only call this request if the corresponding capability `exceptionBreakpointFilters` returns one or more filters.
    public sealed class SetExceptionBreakpointsRequest : Request<SetExceptionBreakpointsArguments>
    {
        public override Dap.Command Command => Dap.Command.SetExceptionBreakpoints;
    }

    /// Obtains information on a possible data breakpoint that could be set on an expression or variable.
    /// Clients should only call this request if the corresponding capability `supportsDataBreakpoints` is true.
    public sealed class DataBreakpointInfoRequest : Request<DataBreakpointInfoArguments>
    {
        public override Dap.Command Command => Dap.Command.DataBreakpointInfo;
    }

    /// Replaces all existing data breakpoints with new data breakpoints.
    /// To clear all data breakpoints, specify an empty array.
    /// When a data breakpoint is hit, a `stopped` event (with reason `data breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsDataBreakpoints` is true.
    public sealed class SetDataBreakpointsRequest : Request<SetDataBreakpointsArguments>
    {
        public override Dap.Command Command => Dap.Command.SetDataBreakpoints;
    }

    /// Replaces all existing instruction breakpoints. Typically, instruction breakpoints would be set from a disassembly window.
    /// To clear all instruction breakpoints, specify an empty array.
    /// When an instruction breakpoint is hit, a `stopped` event (with reason `instruction breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsInstructionBreakpoints` is true.
    public sealed class SetInstructionBreakpointsRequest : Request<SetInstructionBreakpointsArguments>
    {
        public override Dap.Command Command => Dap.Command.SetInstructionBreakpoints;
    }

    /// The request resumes execution of all threads. If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true resumes only the specified thread. If not all threads were resumed, the `allThreadsContinued` attribute of the response should be set to false.
    public sealed class ContinueRequest : Request<ContinueArguments>
    {
        public override Dap.Command Command => Dap.Command.Continue;
    }

    /// The request executes one step (in the given granularity) for the specified thread and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    public sealed class NextRequest : Request<NextArguments>
    {
        public override Dap.Command Command => Dap.Command.Next;
    }

    /// The request resumes the given thread to step into a function/method and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// If the request cannot step into a target, `stepIn` behaves like the `next` request.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    /// If there are multiple function/method calls (or other targets) on the source line,
    /// the argument `targetId` can be used to control into which target the `stepIn` should occur.
    /// The list of possible targets for a given source line can be retrieved via the `stepInTargets` request.
    public sealed class StepInRequest : Request<StepInArguments>
    {
        public override Dap.Command Command => Dap.Command.StepIn;
    }

    /// The request resumes the given thread to step out (return) from a function/method and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    public sealed class StepOutRequest : Request<StepOutArguments>
    {
        public override Dap.Command Command => Dap.Command.StepOut;
    }

    /// The request executes one backward step (in the given granularity) for the specified thread and allows all other threads to run backward freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    /// Clients should only call this request if the corresponding capability `supportsStepBack` is true.
    public sealed class StepBackRequest : Request<StepBackArguments>
    {
        public override Dap.Command Command => Dap.Command.StepBack;
    }

    /// The request resumes backward execution of all threads. If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true resumes only the specified thread. If not all threads were resumed, the `allThreadsContinued` attribute of the response should be set to false.
    /// Clients should only call this request if the corresponding capability `supportsStepBack` is true.
    public sealed class ReverseContinueRequest : Request<ReverseContinueArguments>
    {
        public override Dap.Command Command => Dap.Command.ReverseContinue;
    }

    /// The request restarts execution of the specified stack frame.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `restart`) after the restart has completed.
    /// Clients should only call this request if the corresponding capability `supportsRestartFrame` is true.
    public sealed class RestartFrameRequest : Request<RestartFrameArguments>
    {
        public override Dap.Command Command => Dap.Command.RestartFrame;
    }

    /// The request sets the location where the debuggee will continue to run.
    /// This makes it possible to skip the execution of code or to execute code again.
    /// The code between the current location and the goto target is not executed but skipped.
    /// The debug adapter first sends the response and then a `stopped` event with reason `goto`.
    /// Clients should only call this request if the corresponding capability `supportsGotoTargetsRequest` is true (because only then goto targets exist that can be passed as arguments).
    public sealed class GotoRequest : Request<GotoArguments>
    {
        public override Dap.Command Command => Dap.Command.Goto;
    }

    /// The request suspends the debuggee.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `pause`) after the thread has been paused successfully.
    public sealed class PauseRequest : Request<PauseArguments>
    {
        public override Dap.Command Command => Dap.Command.Pause;
    }

    /// The request returns a stacktrace from the current execution state of a given thread.
    /// A client can request all stack frames by omitting the startFrame and levels arguments. For performance-conscious clients and if the corresponding capability `supportsDelayedStackTraceLoading` is true, stack frames can be retrieved in a piecemeal way with the `startFrame` and `levels` arguments. The response of the `stackTrace` request may contain a `totalFrames` property that hints at the total number of frames in the stack. If a client needs this total number upfront, it can issue a request for a single (first) frame and depending on the value of `totalFrames` decide how to proceed. In any case a client should be prepared to receive fewer frames than requested, which is an indication that the end of the stack has been reached.
    public sealed class StackTraceRequest : Request<StackTraceArguments>
    {
        public override Dap.Command Command => Dap.Command.StackTrace;
    }

    /// The request returns the variable scopes for a given stack frame ID.
    public sealed class ScopesRequest : Request<ScopesArguments>
    {
        public override Dap.Command Command => Dap.Command.Scopes;
    }

    /// Retrieves all child variables for the given variable reference.
    /// A filter can be used to limit the fetched children to either named or indexed children.
    public sealed class VariablesRequest : Request<VariablesArguments>
    {
        public override Dap.Command Command => Dap.Command.Variables;
    }

    /// Set the variable with the given name in the variable container to a new value. Clients should only call this request if the corresponding capability `supportsSetVariable` is true.
    /// If a debug adapter implements both `setVariable` and `setExpression`, a client will only use `setExpression` if the variable has an `evaluateName` property.
    public sealed class SetVariableRequest : Request<SetVariableArguments>
    {
        public override Dap.Command Command => Dap.Command.SetVariable;
    }

    /// The request retrieves the source code for a given source reference.
    public sealed class SourceRequest : Request<SourceArguments>
    {
        public override Dap.Command Command => Dap.Command.Source;
    }

    /// The request retrieves a list of all threads.
    public sealed class ThreadsRequest : Request
    {
        public override Dap.Command Command => Dap.Command.Threads;
    }

    /// The request terminates the threads with the given ids.
    /// Clients should only call this request if the corresponding capability `supportsTerminateThreadsRequest` is true.
    public sealed class TerminateThreadsRequest : Request<TerminateThreadsArguments>
    {
        public override Dap.Command Command => Dap.Command.TerminateThreads;
    }

    /// Modules can be retrieved from the debug adapter with this request which can either return all modules or a range of modules to support paging.
    /// Clients should only call this request if the corresponding capability `supportsModulesRequest` is true.
    public sealed class ModulesRequest : Request<ModulesArguments>
    {
        public override Dap.Command Command => Dap.Command.Modules;
    }

    /// Retrieves the set of all sources currently loaded by the debugged process.
    /// Clients should only call this request if the corresponding capability `supportsLoadedSourcesRequest` is true.
    public sealed class LoadedSourcesRequest : Request<LoadedSourcesArguments>
    {
        public override Dap.Command Command => Dap.Command.LoadedSources;
    }

    /// Evaluates the given expression in the context of a stack frame.
    /// The expression has access to any variables and arguments that are in scope.
    public sealed class EvaluateRequest : Request<EvaluateArguments>
    {
        public override Dap.Command Command => Dap.Command.Evaluate;
    }

    /// Evaluates the given `value` expression and assigns it to the `expression` which must be a modifiable l-value.
    /// The expressions have access to any variables and arguments that are in scope of the specified frame.
    /// Clients should only call this request if the corresponding capability `supportsSetExpression` is true.
    /// If a debug adapter implements both `setExpression` and `setVariable`, a client uses `setExpression` if the variable has an `evaluateName` property.
    public sealed class SetExpressionRequest : Request<SetExpressionArguments>
    {
        public override Dap.Command Command => Dap.Command.SetExpression;
    }

    /// This request retrieves the possible step-in targets for the specified stack frame.
    /// These targets can be used in the `stepIn` request.
    /// Clients should only call this request if the corresponding capability `supportsStepInTargetsRequest` is true.
    public sealed class StepInTargetsRequest : Request<StepInTargetsArguments>
    {
        public override Dap.Command Command => Dap.Command.StepInTargets;
    }

    /// This request retrieves the possible goto targets for the specified source location.
    /// These targets can be used in the `goto` request.
    /// Clients should only call this request if the corresponding capability `supportsGotoTargetsRequest` is true.
    public sealed class GotoTargetsRequest : Request<GotoTargetsArguments>
    {
        public override Dap.Command Command => Dap.Command.GotoTargets;
    }

    /// Returns a list of possible completions for a given caret position and text.
    /// Clients should only call this request if the corresponding capability `supportsCompletionsRequest` is true.
    public sealed class CompletionsRequest : Request<CompletionsArguments>
    {
        public override Dap.Command Command => Dap.Command.Completions;
    }

    /// Retrieves the details of the exception that caused this event to be raised.
    /// Clients should only call this request if the corresponding capability `supportsExceptionInfoRequest` is true.
    public sealed class ExceptionInfoRequest : Request<ExceptionInfoArguments>
    {
        public override Dap.Command Command => Dap.Command.ExceptionInfo;
    }

    /// Reads bytes from memory at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsReadMemoryRequest` is true.
    public sealed class ReadMemoryRequest : Request<ReadMemoryArguments>
    {
        public override Dap.Command Command => Dap.Command.ReadMemory;
    }

    /// Writes bytes to memory at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsWriteMemoryRequest` is true.
    public sealed class WriteMemoryRequest : Request<WriteMemoryArguments>
    {
        public override Dap.Command Command => Dap.Command.WriteMemory;
    }

    /// Disassembles code stored at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsDisassembleRequest` is true.
    public sealed class DisassembleRequest : Request<DisassembleArguments>
    {
        public override Dap.Command Command => Dap.Command.Disassemble;
    }

    /// Looks up information about a location reference previously returned by the debug adapter.
    public sealed class LocationsRequest : Request<LocationsArguments>
    {
        public override Dap.Command Command => Dap.Command.Locations;
    }

    public partial abstract class Response
    {
        private partial static Response ParseInternal(JObject message)
        {
            switch (message.Value<Dap.Command>("command"))
            {
                case Dap.Command.Cancel:
                    return message.ToObject<CancelResponse>();
                case Dap.Command.RunInTerminal:
                    return message.ToObject<RunInTerminalResponse>();
                case Dap.Command.StartDebugging:
                    return message.ToObject<StartDebuggingResponse>();
                case Dap.Command.Initialize:
                    return message.ToObject<InitializeResponse>();
                case Dap.Command.ConfigurationDone:
                    return message.ToObject<ConfigurationDoneResponse>();
                case Dap.Command.Launch:
                    return message.ToObject<LaunchResponse>();
                case Dap.Command.Attach:
                    return message.ToObject<AttachResponse>();
                case Dap.Command.Restart:
                    return message.ToObject<RestartResponse>();
                case Dap.Command.Disconnect:
                    return message.ToObject<DisconnectResponse>();
                case Dap.Command.Terminate:
                    return message.ToObject<TerminateResponse>();
                case Dap.Command.BreakpointLocations:
                    return message.ToObject<BreakpointLocationsResponse>();
                case Dap.Command.SetBreakpoints:
                    return message.ToObject<SetBreakpointsResponse>();
                case Dap.Command.SetFunctionBreakpoints:
                    return message.ToObject<SetFunctionBreakpointsResponse>();
                case Dap.Command.SetExceptionBreakpoints:
                    return message.ToObject<SetExceptionBreakpointsResponse>();
                case Dap.Command.DataBreakpointInfo:
                    return message.ToObject<DataBreakpointInfoResponse>();
                case Dap.Command.SetDataBreakpoints:
                    return message.ToObject<SetDataBreakpointsResponse>();
                case Dap.Command.SetInstructionBreakpoints:
                    return message.ToObject<SetInstructionBreakpointsResponse>();
                case Dap.Command.Continue:
                    return message.ToObject<ContinueResponse>();
                case Dap.Command.Next:
                    return message.ToObject<NextResponse>();
                case Dap.Command.StepIn:
                    return message.ToObject<StepInResponse>();
                case Dap.Command.StepOut:
                    return message.ToObject<StepOutResponse>();
                case Dap.Command.StepBack:
                    return message.ToObject<StepBackResponse>();
                case Dap.Command.ReverseContinue:
                    return message.ToObject<ReverseContinueResponse>();
                case Dap.Command.RestartFrame:
                    return message.ToObject<RestartFrameResponse>();
                case Dap.Command.Goto:
                    return message.ToObject<GotoResponse>();
                case Dap.Command.Pause:
                    return message.ToObject<PauseResponse>();
                case Dap.Command.StackTrace:
                    return message.ToObject<StackTraceResponse>();
                case Dap.Command.Scopes:
                    return message.ToObject<ScopesResponse>();
                case Dap.Command.Variables:
                    return message.ToObject<VariablesResponse>();
                case Dap.Command.SetVariable:
                    return message.ToObject<SetVariableResponse>();
                case Dap.Command.Source:
                    return message.ToObject<SourceResponse>();
                case Dap.Command.Threads:
                    return message.ToObject<ThreadsResponse>();
                case Dap.Command.TerminateThreads:
                    return message.ToObject<TerminateThreadsResponse>();
                case Dap.Command.Modules:
                    return message.ToObject<ModulesResponse>();
                case Dap.Command.LoadedSources:
                    return message.ToObject<LoadedSourcesResponse>();
                case Dap.Command.Evaluate:
                    return message.ToObject<EvaluateResponse>();
                case Dap.Command.SetExpression:
                    return message.ToObject<SetExpressionResponse>();
                case Dap.Command.StepInTargets:
                    return message.ToObject<StepInTargetsResponse>();
                case Dap.Command.GotoTargets:
                    return message.ToObject<GotoTargetsResponse>();
                case Dap.Command.Completions:
                    return message.ToObject<CompletionsResponse>();
                case Dap.Command.ExceptionInfo:
                    return message.ToObject<ExceptionInfoResponse>();
                case Dap.Command.ReadMemory:
                    return message.ToObject<ReadMemoryResponse>();
                case Dap.Command.WriteMemory:
                    return message.ToObject<WriteMemoryResponse>();
                case Dap.Command.Disassemble:
                    return message.ToObject<DisassembleResponse>();
                case Dap.Command.Locations:
                    return message.ToObject<LocationsResponse>();
                default:
                    throw new Exception($"unknown response command: {command}");
            }
        }
    }

    /// The `cancel` request is used by the client in two situations:
    /// - to indicate that it is no longer interested in the result produced by a specific request issued earlier
    /// - to cancel a progress sequence.
    /// Clients should only call this request if the corresponding capability `supportsCancelRequest` is true.
    /// This request has a hint characteristic: a debug adapter can only be expected to make a 'best effort' in honoring this request but there are no guarantees.
    /// The `cancel` request may return an error if it could not cancel an operation but a client should refrain from presenting this error to end users.
    /// The request that got cancelled still needs to send a response back. This can either be a normal result (`success` attribute true) or an error response (`success` attribute false and the `message` set to `cancelled`).
    /// Returning partial results from a cancelled request is possible but please note that a client has no generic way for detecting that a response is partial or not.
    /// The progress that got cancelled still needs to send a `progressEnd` event back.
    ///  A client should not assume that progress just got cancelled after sending the `cancel` request.
    public sealed class CancelResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Cancel;
    }

    /// This request is sent from the debug adapter to the client to run a command in a terminal.
    /// This is typically used to launch the debuggee in a terminal provided by the client.
    /// This request should only be called if the corresponding client capability `supportsRunInTerminalRequest` is true.
    /// Client implementations of `runInTerminal` are free to run the command however they choose including issuing the command to a command line interpreter (aka 'shell'). Argument strings passed to the `runInTerminal` request must arrive verbatim in the command to be run. As a consequence, clients which use a shell are responsible for escaping any special shell characters in the argument strings to prevent them from being interpreted (and modified) by the shell.
    /// Some users may wish to take advantage of shell processing in the argument strings. For clients which implement `runInTerminal` using an intermediary shell, the `argsCanBeInterpretedByShell` property can be set to true. In this case the client is requested not to escape any special shell characters in the argument strings.
    public sealed class RunInTerminalResponse : Response
    {
        public override Dap.Command Command => Dap.Command.RunInTerminal;
    }

    /// This request is sent from the debug adapter to the client to start a new debug session of the same type as the caller.
    /// This request should only be sent if the corresponding client capability `supportsStartDebuggingRequest` is true.
    /// A client implementation of `startDebugging` should start a new debug session (of the same type as the caller) in the same way that the caller's session was started. If the client supports hierarchical debug sessions, the newly created session can be treated as a child of the caller session.
    public sealed class StartDebuggingResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StartDebugging;
    }

    /// The `initialize` request is sent as the first request from the client to the debug adapter in order to configure it with client capabilities and to retrieve capabilities from the debug adapter.
    /// Until the debug adapter has responded with an `initialize` response, the client must not send any additional requests or events to the debug adapter.
    /// In addition the debug adapter is not allowed to send any requests or events to the client until it has responded with an `initialize` response.
    /// The `initialize` request may only be sent once.
    public sealed class InitializeResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Initialize;
    }

    /// This request indicates that the client has finished initialization of the debug adapter.
    /// So it is the last request in the sequence of configuration requests (which was started by the `initialized` event).
    /// Clients should only call this request if the corresponding capability `supportsConfigurationDoneRequest` is true.
    public sealed class ConfigurationDoneResponse : Response
    {
        public override Dap.Command Command => Dap.Command.ConfigurationDone;
    }

    /// This launch request is sent from the client to the debug adapter to start the debuggee with or without debugging (if `noDebug` is true).
    /// Since launching is debugger/runtime specific, the arguments for this request are not part of this specification.
    public sealed class LaunchResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Launch;
    }

    /// The `attach` request is sent from the client to the debug adapter to attach to a debuggee that is already running.
    /// Since attaching is debugger/runtime specific, the arguments for this request are not part of this specification.
    public sealed class AttachResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Attach;
    }

    /// Restarts a debug session. Clients should only call this request if the corresponding capability `supportsRestartRequest` is true.
    /// If the capability is missing or has the value false, a typical client emulates `restart` by terminating the debug adapter first and then launching it anew.
    public sealed class RestartResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Restart;
    }

    /// The `disconnect` request asks the debug adapter to disconnect from the debuggee (thus ending the debug session) and then to shut down itself (the debug adapter).
    /// In addition, the debug adapter must terminate the debuggee if it was started with the `launch` request. If an `attach` request was used to connect to the debuggee, then the debug adapter must not terminate the debuggee.
    /// This implicit behavior of when to terminate the debuggee can be overridden with the `terminateDebuggee` argument (which is only supported by a debug adapter if the corresponding capability `supportTerminateDebuggee` is true).
    public sealed class DisconnectResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Disconnect;
    }

    /// The `terminate` request is sent from the client to the debug adapter in order to shut down the debuggee gracefully. Clients should only call this request if the capability `supportsTerminateRequest` is true.
    /// Typically a debug adapter implements `terminate` by sending a software signal which the debuggee intercepts in order to clean things up properly before terminating itself.
    /// Please note that this request does not directly affect the state of the debug session: if the debuggee decides to veto the graceful shutdown for any reason by not terminating itself, then the debug session just continues.
    /// Clients can surface the `terminate` request as an explicit command or they can integrate it into a two stage Stop command that first sends `terminate` to request a graceful shutdown, and if that fails uses `disconnect` for a forceful shutdown.
    public sealed class TerminateResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Terminate;
    }

    /// The `breakpointLocations` request returns all possible locations for source breakpoints in a given range.
    /// Clients should only call this request if the corresponding capability `supportsBreakpointLocationsRequest` is true.
    public sealed class BreakpointLocationsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.BreakpointLocations;
    }

    /// Sets multiple breakpoints for a single source and clears all previous breakpoints in that source.
    /// To clear all breakpoint for a source, specify an empty array.
    /// When a breakpoint is hit, a `stopped` event (with reason `breakpoint`) is generated.
    public sealed class SetBreakpointsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetBreakpoints;
    }

    /// Replaces all existing function breakpoints with new function breakpoints.
    /// To clear all function breakpoints, specify an empty array.
    /// When a function breakpoint is hit, a `stopped` event (with reason `function breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsFunctionBreakpoints` is true.
    public sealed class SetFunctionBreakpointsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetFunctionBreakpoints;
    }

    /// The request configures the debugger's response to thrown exceptions. Each of the `filters`, `filterOptions`, and `exceptionOptions` in the request are independent configurations to a debug adapter indicating a kind of exception to catch. An exception thrown in a program should result in a `stopped` event from the debug adapter (with reason `exception`) if any of the configured filters match.
    /// Clients should only call this request if the corresponding capability `exceptionBreakpointFilters` returns one or more filters.
    public sealed class SetExceptionBreakpointsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetExceptionBreakpoints;
    }

    /// Obtains information on a possible data breakpoint that could be set on an expression or variable.
    /// Clients should only call this request if the corresponding capability `supportsDataBreakpoints` is true.
    public sealed class DataBreakpointInfoResponse : Response
    {
        public override Dap.Command Command => Dap.Command.DataBreakpointInfo;
    }

    /// Replaces all existing data breakpoints with new data breakpoints.
    /// To clear all data breakpoints, specify an empty array.
    /// When a data breakpoint is hit, a `stopped` event (with reason `data breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsDataBreakpoints` is true.
    public sealed class SetDataBreakpointsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetDataBreakpoints;
    }

    /// Replaces all existing instruction breakpoints. Typically, instruction breakpoints would be set from a disassembly window.
    /// To clear all instruction breakpoints, specify an empty array.
    /// When an instruction breakpoint is hit, a `stopped` event (with reason `instruction breakpoint`) is generated.
    /// Clients should only call this request if the corresponding capability `supportsInstructionBreakpoints` is true.
    public sealed class SetInstructionBreakpointsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetInstructionBreakpoints;
    }

    /// The request resumes execution of all threads. If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true resumes only the specified thread. If not all threads were resumed, the `allThreadsContinued` attribute of the response should be set to false.
    public sealed class ContinueResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Continue;
    }

    /// The request executes one step (in the given granularity) for the specified thread and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    public sealed class NextResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Next;
    }

    /// The request resumes the given thread to step into a function/method and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// If the request cannot step into a target, `stepIn` behaves like the `next` request.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    /// If there are multiple function/method calls (or other targets) on the source line,
    /// the argument `targetId` can be used to control into which target the `stepIn` should occur.
    /// The list of possible targets for a given source line can be retrieved via the `stepInTargets` request.
    public sealed class StepInResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StepIn;
    }

    /// The request resumes the given thread to step out (return) from a function/method and allows all other threads to run freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    public sealed class StepOutResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StepOut;
    }

    /// The request executes one backward step (in the given granularity) for the specified thread and allows all other threads to run backward freely by resuming them.
    /// If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true prevents other suspended threads from resuming.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `step`) after the step has completed.
    /// Clients should only call this request if the corresponding capability `supportsStepBack` is true.
    public sealed class StepBackResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StepBack;
    }

    /// The request resumes backward execution of all threads. If the debug adapter supports single thread execution (see capability `supportsSingleThreadExecutionRequests`), setting the `singleThread` argument to true resumes only the specified thread. If not all threads were resumed, the `allThreadsContinued` attribute of the response should be set to false.
    /// Clients should only call this request if the corresponding capability `supportsStepBack` is true.
    public sealed class ReverseContinueResponse : Response
    {
        public override Dap.Command Command => Dap.Command.ReverseContinue;
    }

    /// The request restarts execution of the specified stack frame.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `restart`) after the restart has completed.
    /// Clients should only call this request if the corresponding capability `supportsRestartFrame` is true.
    public sealed class RestartFrameResponse : Response
    {
        public override Dap.Command Command => Dap.Command.RestartFrame;
    }

    /// The request sets the location where the debuggee will continue to run.
    /// This makes it possible to skip the execution of code or to execute code again.
    /// The code between the current location and the goto target is not executed but skipped.
    /// The debug adapter first sends the response and then a `stopped` event with reason `goto`.
    /// Clients should only call this request if the corresponding capability `supportsGotoTargetsRequest` is true (because only then goto targets exist that can be passed as arguments).
    public sealed class GotoResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Goto;
    }

    /// The request suspends the debuggee.
    /// The debug adapter first sends the response and then a `stopped` event (with reason `pause`) after the thread has been paused successfully.
    public sealed class PauseResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Pause;
    }

    /// The request returns a stacktrace from the current execution state of a given thread.
    /// A client can request all stack frames by omitting the startFrame and levels arguments. For performance-conscious clients and if the corresponding capability `supportsDelayedStackTraceLoading` is true, stack frames can be retrieved in a piecemeal way with the `startFrame` and `levels` arguments. The response of the `stackTrace` request may contain a `totalFrames` property that hints at the total number of frames in the stack. If a client needs this total number upfront, it can issue a request for a single (first) frame and depending on the value of `totalFrames` decide how to proceed. In any case a client should be prepared to receive fewer frames than requested, which is an indication that the end of the stack has been reached.
    public sealed class StackTraceResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StackTrace;
    }

    /// The request returns the variable scopes for a given stack frame ID.
    public sealed class ScopesResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Scopes;
    }

    /// Retrieves all child variables for the given variable reference.
    /// A filter can be used to limit the fetched children to either named or indexed children.
    public sealed class VariablesResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Variables;
    }

    /// Set the variable with the given name in the variable container to a new value. Clients should only call this request if the corresponding capability `supportsSetVariable` is true.
    /// If a debug adapter implements both `setVariable` and `setExpression`, a client will only use `setExpression` if the variable has an `evaluateName` property.
    public sealed class SetVariableResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetVariable;
    }

    /// The request retrieves the source code for a given source reference.
    public sealed class SourceResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Source;
    }

    /// The request retrieves a list of all threads.
    public sealed class ThreadsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Threads;
    }

    /// The request terminates the threads with the given ids.
    /// Clients should only call this request if the corresponding capability `supportsTerminateThreadsRequest` is true.
    public sealed class TerminateThreadsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.TerminateThreads;
    }

    /// Modules can be retrieved from the debug adapter with this request which can either return all modules or a range of modules to support paging.
    /// Clients should only call this request if the corresponding capability `supportsModulesRequest` is true.
    public sealed class ModulesResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Modules;
    }

    /// Retrieves the set of all sources currently loaded by the debugged process.
    /// Clients should only call this request if the corresponding capability `supportsLoadedSourcesRequest` is true.
    public sealed class LoadedSourcesResponse : Response
    {
        public override Dap.Command Command => Dap.Command.LoadedSources;
    }

    /// Evaluates the given expression in the context of a stack frame.
    /// The expression has access to any variables and arguments that are in scope.
    public sealed class EvaluateResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Evaluate;
    }

    /// Evaluates the given `value` expression and assigns it to the `expression` which must be a modifiable l-value.
    /// The expressions have access to any variables and arguments that are in scope of the specified frame.
    /// Clients should only call this request if the corresponding capability `supportsSetExpression` is true.
    /// If a debug adapter implements both `setExpression` and `setVariable`, a client uses `setExpression` if the variable has an `evaluateName` property.
    public sealed class SetExpressionResponse : Response
    {
        public override Dap.Command Command => Dap.Command.SetExpression;
    }

    /// This request retrieves the possible step-in targets for the specified stack frame.
    /// These targets can be used in the `stepIn` request.
    /// Clients should only call this request if the corresponding capability `supportsStepInTargetsRequest` is true.
    public sealed class StepInTargetsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.StepInTargets;
    }

    /// This request retrieves the possible goto targets for the specified source location.
    /// These targets can be used in the `goto` request.
    /// Clients should only call this request if the corresponding capability `supportsGotoTargetsRequest` is true.
    public sealed class GotoTargetsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.GotoTargets;
    }

    /// Returns a list of possible completions for a given caret position and text.
    /// Clients should only call this request if the corresponding capability `supportsCompletionsRequest` is true.
    public sealed class CompletionsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Completions;
    }

    /// Retrieves the details of the exception that caused this event to be raised.
    /// Clients should only call this request if the corresponding capability `supportsExceptionInfoRequest` is true.
    public sealed class ExceptionInfoResponse : Response
    {
        public override Dap.Command Command => Dap.Command.ExceptionInfo;
    }

    /// Reads bytes from memory at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsReadMemoryRequest` is true.
    public sealed class ReadMemoryResponse : Response
    {
        public override Dap.Command Command => Dap.Command.ReadMemory;
    }

    /// Writes bytes to memory at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsWriteMemoryRequest` is true.
    public sealed class WriteMemoryResponse : Response
    {
        public override Dap.Command Command => Dap.Command.WriteMemory;
    }

    /// Disassembles code stored at the provided location.
    /// Clients should only call this request if the corresponding capability `supportsDisassembleRequest` is true.
    public sealed class DisassembleResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Disassemble;
    }

    /// Looks up information about a location reference previously returned by the debug adapter.
    public sealed class LocationsResponse : Response
    {
        public override Dap.Command Command => Dap.Command.Locations;
    }
}
